### ISSUE TITLE
Update DB checks

### ISSUE THREAD

**Issue by rndquu** [ubiquity/faucet#2]
Depends on https://github.com/ubiquity/ubiquibot/pull/644

The https://github.com/ubiquity/ubiquibot/pull/644 PR introduces DB field updates. When https://github.com/ubiquity/ubiquibot/pull/644 is implemented we should make sure that the following conditions are not broken due to DB field renamins:
- https://github.com/ubiquity/faucet/blob/0efe857822dde40d63913ceb379babf43f6960e9/src/index.ts#L46
- https://github.com/ubiquity/faucet/blob/0efe857822dde40d63913ceb379babf43f6960e9/src/index.ts#L55

**Comment by 0x4007** [comment]
I think it will be my responsibility by default to ensure that the database calls are all valid in the refactor. 

However this week I can't code much and have been thinking about delegating the task to refactor the database calls. 

We are still waiting for one fairly major adjustment by @wannacfuture which delegates the long running compute of certain operations (like parsing comments and calculating the comment incentives) to a GitHub Actions runner. 

That way the bot kernel runs quick operations within Netlify and delegates to GitHub Actions for slow running operations including all the AI related operations.  

After that is complete, the last major step is refactoring the database calls (any takers?)

**Comment by devpanther** [comment]
> After that is complete, the last major step is refactoring the database calls (any takers?)

I'm up for it, the database schema update is still pending or has it been completed in-house?

**Comment by 0x4007** [comment]
> > After that is complete, the last major step is refactoring the database calls (any takers?)
> 
> 
> 
> I'm up for it, the database schema update is still pending or has it been completed in-house?

It is complete. I recommend you set up a new database and then apply the schema backup: 

https://t.me/UbiquityDAO/29891/31504

Be sure to work off of my latest commit on my fork, refer to Git Graph extension on vscode. 

I believe it is `feat/contributor-incentives-total-scoring`

**Comment by gentlementlegen** [comment]
The code change seems pretty straightforward, but I am not sure about the `"aws-sdk": "link:stub"` in the package.json, what is it exactly?

**Comment by rndquu** [comment]
> The code change seems pretty straightforward, but I am not sure about the `"aws-sdk": "link:stub"` in the package.json, what is it exactly?

As far as I remember this is a requirement for one of the cloudflare npm packages due to some bug. This is solely for build purposes since `"aws-sdk": "link:stub"` references an empty file. @Keyrxng might now better.

**Comment by Keyrxng** [comment]
It's to do with the patch that gets applied to adjust axios and oz defender to run in Deno I'm sure if I remember correctly. It's those two packages anyway and I assumed it was for running in a Deno env but may be for another reason

the patch updates axios fetch and I forget off the top of my head what gets changed in defender it may be the same thing

but yeah there for build reasons, it's referenced in the pnpm.lock
